server:
  port: 8001
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        #same-site: none
        #secure: true
spring:
  application:
    name: user-center
  profiles:
    active: dev
  # Redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 123456
  # Session失效时间（分钟）
  session:
    timeout: 120
    # 将Session存储到redis
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.134:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # 整合Swagger需要添加的配置，springboot version >= 2.6
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  # sqlSessionFactory需要配置起别名注解@Alias扫描的路径
  typeAliasesPackage: com.dongdong.usercenter.model.*
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #字段策略 0:"忽略判断",1:"非 NULL 判断，通过接口更新数据时数据为NULL值时将不更新进数据库。默认策略",2:"非空判断"
    field-strategy: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

com:
  dongdong:
    usercenter:
      business:
        matchNumber: 6